import {
  CourseLevel,
  CourseStatus,
  ICoach,
} from "@/interfaces";

export const coachDashboardData: ICoach = {
  id: "coach-1",
  firstName: "Mohammad",
  lastName: "Ahadiyan",
  email: "m.ahadiyan@coachos.dev",
  role: "COACH",
  avatarUrl: "https://i.pravatar.cc/120?img=12",
  createdAt: "2026-01-10T08:00:00Z",
  updatedAt: "2026-08-11T09:20:00Z",
  trainees: [
    {
      id: "trainee-1",
      avatar: "https://i.pravatar.cc/150?img=1",
      name: "Alex Johnson",
      courseName: "Strength Training",
      courseNumber: 101,
      status: CourseStatus.COMP,
      level: CourseLevel.MED,
      updatedAt: "2026-08-09T18:30:00Z",
    },
    {
      id: "trainee-2",
      avatar: "https://i.pravatar.cc/150?img=2",
      name: "Sarah Williams",
      courseName: "Cardio Basics",
      courseNumber: 102,
      status: CourseStatus.PROG,
      level: CourseLevel.EZ,
      updatedAt: "2026-08-09T16:45:00Z",
    },
    {
      id: "trainee-3",
      avatar: "https://i.pravatar.cc/150?img=3",
      name: "Michael Brown",
      courseName: "Advanced Strength",
      courseNumber: 103,
      status: CourseStatus.PEND,
      level: CourseLevel.HARD,
      updatedAt: "2026-08-08T12:20:00Z",
    },
    {
      id: "trainee-4",
      avatar: "https://i.pravatar.cc/150?img=4",
      name: "Emily Davis",
      courseName: "Yoga and Flexibility",
      courseNumber: 104,
      status: CourseStatus.COMP,
      level: CourseLevel.EZ,
      updatedAt: "2026-08-08T09:15:00Z",
    },
    {
      id: "trainee-5",
      avatar: "https://i.pravatar.cc/150?img=5",
      name: "Daniel Wilson",
      courseName: "HIIT Workout",
      courseNumber: 105,
      status: CourseStatus.FAILD,
      level: CourseLevel.HARD,
      updatedAt: "2026-08-07T21:10:00Z",
    },
    {
      id: "trainee-6",
      avatar: "https://i.pravatar.cc/150?img=6",
      name: "Olivia Martinez",
      courseName: "Weight Loss Program",
      courseNumber: 106,
      status: CourseStatus.PROG,
      level: CourseLevel.MED,
      updatedAt: "2026-08-07T17:35:00Z",
    },
  ],
  messages: [
    {
      id: "message-1",
      sender: "Ava Rahimi",
      content:
        "Coach, I finished yesterday's mobility work and uploaded my progress video.",
      time: "08:30",
    },
    {
      id: "message-2",
      sender: "Reza Mohammadi",
      content: "Can we move today's session to 5:30 PM? I have a meeting overlap.",
      time: "09:10",
    },
    {
      id: "message-3",
      sender: "Sara Azimi",
      content:
        "My knee feels better this week. Should I increase squat load in tomorrow's plan?",
      time: "10:02",
    },
  ],
  activeCourses: [
    {
      id: "course-1",
      title: "Strength Foundations",
      status: CourseStatus.PROG,
      elapsed: 34,
      remaining: 22,
      completion: 61,
    },
    {
      id: "course-2",
      title: "Mobility Reset",
      status: CourseStatus.PEND,
      elapsed: 6,
      remaining: 36,
      completion: 14,
    },
    {
      id: "course-3",
      title: "Endurance Builder",
      status: CourseStatus.FAILD,
      elapsed: 39,
      remaining: 21,
      completion: 65,
    },
    {
      id: "course-4",
      title: "Core Stability",
      status: CourseStatus.PROG,
      elapsed: 20,
      remaining: 15,
      completion: 57,
    },
    {
      id: "course-5",
      title: "Weight Management",
      status: CourseStatus.PROG,
      elapsed: 22,
      remaining: 28,
      completion: 44,
    },
    {
      id: "course-6",
      title: "Injury Recovery",
      status: CourseStatus.COMP,
      elapsed: 45,
      remaining: 0,
      completion: 100,
    },
  ],
};
